version: '3.3'

services:
  app_name:
    image: hisiter/lawrag-devcontainers
    networks:
      app_name:
    volumes:
      - .:/workspace
    environment:
      - DEBUG=1
      - DJANGO_CONFIGURATION=development
    ports:
      - 7777:7000
networks:
  app_name:
